# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk11
# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту kasian.job@gmail.com если сборка упала
notifications:
  email:
    recipients:
      kasian.job@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

env:
  global:
    CODECOV_TOKEN="39f37a40-3f15-4312-9dc8-02e733591981"
